"""m

Revision ID: 2639c9a63223
Revises: 
Create Date: 2026-03-09 21:29:35.205675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2639c9a63223'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('booking', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('booking_ibfk_3'), 'booking', type_='foreignkey')
    op.drop_constraint(op.f('booking_ibfk_2'), 'booking', type_='foreignkey')
    op.drop_constraint(op.f('booking_ibfk_1'), 'booking', type_='foreignkey')
    op.add_column('guests', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('guests', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('email'), table_name='guests')
    op.drop_index(op.f('email_2'), table_name='guests')
    op.drop_index(op.f('phone'), table_name='guests')
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('payments', 'paid_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_constraint(op.f('payments_ibfk_1'), 'payments', type_='foreignkey')
    op.add_column('room_occupancy', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('room_occupancy', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('room_occupancy_ibfk_2'), 'room_occupancy', type_='foreignkey')
    op.drop_constraint(op.f('room_occupancy_ibfk_1'), 'room_occupancy', type_='foreignkey')
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('staff', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('staff', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'updated_at')
    op.drop_column('staff', 'created_at')
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'created_at')
    op.create_foreign_key(op.f('room_occupancy_ibfk_1'), 'room_occupancy', 'rooms', ['room_id'], ['room_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('room_occupancy_ibfk_2'), 'room_occupancy', 'booking', ['booking_id'], ['booking_id'], ondelete='CASCADE')
    op.drop_column('room_occupancy', 'updated_at')
    op.drop_column('room_occupancy', 'created_at')
    op.create_foreign_key(op.f('payments_ibfk_1'), 'payments', 'booking', ['booking_id'], ['booking_id'], ondelete='CASCADE')
    op.alter_column('payments', 'paid_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_column('payments', 'updated_at')
    op.create_index(op.f('phone'), 'guests', ['phone'], unique=True)
    op.create_index(op.f('email_2'), 'guests', ['email'], unique=True)
    op.create_index(op.f('email'), 'guests', ['email'], unique=True)
    op.alter_column('guests', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_column('guests', 'updated_at')
    op.create_foreign_key(op.f('booking_ibfk_1'), 'booking', 'guests', ['guest_id'], ['guest_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('booking_ibfk_2'), 'booking', 'rooms', ['room_id'], ['room_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('booking_ibfk_3'), 'booking', 'staff', ['staff_id'], ['staff_id'], ondelete='CASCADE')
    op.drop_column('booking', 'updated_at')
    op.drop_column('booking', 'created_at')
    # ### end Alembic commands ###
